### ISSUE TITLE
无ios端么？

### ISSUE THREAD

**Issue by X-Fan-Jack** [StupidTrees/HITA_X#16]
如题

**Comment by X-Fan-Jack** [comment]
再加一个：好像官网炸了

**Comment by StupidTrees** [comment]
ios之前有学弟做了，续不起费就下了。官网也是，域名过期了续不起费就下了。

**Comment by X-Fan-Jack** [comment]
那请问IOS有其他的替代方案么？  官方的app实在是nt

**Comment by StupidTrees** [comment]
IOS课表的作者联系方式是2593475337@qq.com只是课表的话，[doby.tech](https://doby.tech/) 这个应该可以。另外一个很笨的workaround是用安卓app导出课表的ICS文件导入IOS。

**Comment by X-Fan-Jack** [comment]
感谢提供的支持。  我这边课因为不是很多，所以用GoogleCalendar做替代方案了..  。
再次感谢您的支持，这个issue可以close 了
